import Foundation
import AppKit
import ApplicationServices

public final class TextInserter {
    public static let shared = TextInserter()

    // Standard macOS pasteboard markers recognized by clipboard history managers
    // (Raycast, Alfred, Maccy, Paste, CleanClip, Pastebot, LaunchBar, etc.) to IGNORE this clip
    private let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    private let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    private init() {}

    private struct SavedPasteboardItem {
        let types: [NSPasteboard.PasteboardType]
        let dataByType: [NSPasteboard.PasteboardType: Data]
    }

    /// Captures all items currently on the system clipboard
    private func snapshotPasteboard() -> [SavedPasteboardItem] {
        let pasteboard = NSPasteboard.general
        guard let items = pasteboard.pasteboardItems else { return [] }
        var snapshot: [SavedPasteboardItem] = []
        for item in items {
            var dataDict: [NSPasteboard.PasteboardType: Data] = [:]
            for type in item.types {
                if let data = item.data(forType: type) {
                    dataDict[type] = data
                }
            }
            snapshot.append(SavedPasteboardItem(types: item.types, dataByType: dataDict))
        }
        return snapshot
    }

    /// Restores the pasteboard to the captured snapshot
    private func restorePasteboard(from snapshot: [SavedPasteboardItem]) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        guard !snapshot.isEmpty else { return }

        var restoredItems: [NSPasteboardItem] = []
        for saved in snapshot {
            let item = NSPasteboardItem()
            for type in saved.types {
                if let data = saved.dataByType[type] {
                    item.setData(data, forType: type)
                }
            }
            restoredItems.append(item)
        }
        if !restoredItems.isEmpty {
            pasteboard.writeObjects(restoredItems)
        }
    }

    /// Inserts text directly into the active application wherever the cursor is located.
    ///
    /// - Parameters:
    ///   - text: The text to insert.
    ///   - keepOnClipboard: If false (Whisperflow-style default), Metatron marks the pasteboard item
    ///     as transient so clipboard history managers (Raycast, Alfred, Maccy, etc.) ignore it,
    ///     and restores the user's prior clipboard 180ms after Cmd+V is dispatched.
    ///     If true, the text remains on the system clipboard permanently.
    ///   - completion: Optional callback when insertion and clipboard restoration are complete.
    public func insertText(
        _ text: String,
        keepOnClipboard: Bool = false,
        completion: (() -> Void)? = nil
    ) {
        guard !text.isEmpty else {
            completion?()
            return
        }

        let pasteboard = NSPasteboard.general
        let shouldRestore = !keepOnClipboard
        let previousSnapshot = shouldRestore ? snapshotPasteboard() : []

        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)

        if shouldRestore {
            // Signal to all macOS clipboard managers (Raycast, Alfred, Maccy, Paste, CleanClip, etc.)
            // that this is a transient/auto-generated paste and MUST NOT be recorded into history.
            item.setString("", forType: transientType)
            item.setString("", forType: concealedType)
            item.setString("", forType: autoGeneratedType)
        }

        pasteboard.writeObjects([item])
        let changeCountAfterWrite = pasteboard.changeCount

        // Wait 25ms for the macOS pasteboard server to register the new item before sending Cmd+V
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.025) {
            self.sendPasteKeystroke()

            if shouldRestore {
                // Allow the target application 180ms to read from the pasteboard, then restore prior clipboard
                DispatchQueue.main.asyncAfter(deadline: .now() + 0.18) {
                    // Safety check: Only restore if the user hasn't copied something else in those 180ms
                    if pasteboard.changeCount == changeCountAfterWrite {
                        self.restorePasteboard(from: previousSnapshot)
                    }
                    completion?()
                }
            } else {
                completion?()
            }
        }
    }

    /// Synthesizes Command + V keypress events into the focused application
    public func sendPasteKeystroke() {
        let vKeyCode: CGKeyCode = 9 // 'v' virtual key code on macOS

        let source = CGEventSource(stateID: .combinedSessionState)
        let keyDown = CGEvent(keyboardEventSource: source, virtualKey: vKeyCode, keyDown: true)
        keyDown?.flags = .maskCommand

        let keyUp = CGEvent(keyboardEventSource: source, virtualKey: vKeyCode, keyDown: false)
        keyUp?.flags = .maskCommand

        keyDown?.post(tap: .cghidEventTap)
        keyUp?.post(tap: .cghidEventTap)
    }
}
