import Foundation
import AppKit
import ApplicationServices

public final class TextInserter {
    public static let shared = TextInserter()

    // Standard macOS pasteboard markers recognized by clipboard history managers
    // (Raycast, Alfred, Maccy, Paste, CleanClip, Pastebot, LaunchBar, etc.) to IGNORE this clip
    private let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    private let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    private init() {}

    private func logDuration(_ stage: String, since started: TimeInterval) {
        let milliseconds = (ProcessInfo.processInfo.systemUptime - started) * 1_000
        NSLog("[Metatron] Insertion timing %@=%.1fms", stage, milliseconds)
    }

    private struct SavedPasteboardItem {
        let types: [NSPasteboard.PasteboardType]
        let dataByType: [NSPasteboard.PasteboardType: Data]
    }

    /// Captures all items currently on the system clipboard
    private func snapshotPasteboard() -> [SavedPasteboardItem] {
        let pasteboard = NSPasteboard.general
        guard let items = pasteboard.pasteboardItems else { return [] }
        var snapshot: [SavedPasteboardItem] = []
        for item in items {
            var dataDict: [NSPasteboard.PasteboardType: Data] = [:]
            for type in item.types {
                if let data = item.data(forType: type) {
                    dataDict[type] = data
                }
            }
            snapshot.append(SavedPasteboardItem(types: item.types, dataByType: dataDict))
        }
        return snapshot
    }

    /// Restores the pasteboard to the captured snapshot
    private func restorePasteboard(from snapshot: [SavedPasteboardItem]) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        guard !snapshot.isEmpty else { return }

        var restoredItems: [NSPasteboardItem] = []
        for saved in snapshot {
            let item = NSPasteboardItem()
            for type in saved.types {
                if let data = saved.dataByType[type] {
                    item.setData(data, forType: type)
                }
            }
            restoredItems.append(item)
        }
        if !restoredItems.isEmpty {
            pasteboard.writeObjects(restoredItems)
        }
    }

    /// Inserts text into the application and control focused at the time of this call.
    ///
    /// - Parameters:
    ///   - text: The text to insert.
    ///   - keepOnClipboard: If false (Whisperflow-style default), Metatron marks the pasteboard item
    ///     as transient so clipboard history managers (Raycast, Alfred, Maccy, etc.) ignore it,
    ///     and restores the user's prior clipboard 180ms after Cmd+V is dispatched.
    ///     If true, the text remains on the system clipboard permanently.
    ///   - completion: Optional callback when insertion and clipboard restoration are complete.
    public func insertText(
        _ text: String,
        keepOnClipboard: Bool = false,
        completion: (() -> Void)? = nil
    ) {
        insertText(text, keepOnClipboard: keepOnClipboard, target: InsertionTarget.capture(), completion: { _ in
            completion?()
        })
    }

    /// Queues a paste only while the original dictation destination is still focused.
    /// A nil target fails closed. `shouldInsert` can invalidate a cancelled recording
    /// immediately before dispatch. Completion reports whether Cmd+V was dispatched.
    /// The return value reports whether an insertion was queued, not whether it finished.
    @discardableResult
    public func insertText(
        _ text: String,
        keepOnClipboard: Bool = false,
        target: InsertionTarget?,
        shouldInsert: (() -> Bool)? = nil,
        completion: ((Bool) -> Void)? = nil
    ) -> Bool {
        let insertionStarted = ProcessInfo.processInfo.systemUptime
        let initialCheckStarted = ProcessInfo.processInfo.systemUptime
        let targetIsCurrent = target?.isCurrent == true
        let canInsert = !text.isEmpty && targetIsCurrent && shouldInsert?() != false
        logDuration("initial_focus", since: initialCheckStarted)
        guard canInsert else {
            logDuration("total", since: insertionStarted)
            completion?(false)
            return false
        }

        let pasteboard = NSPasteboard.general
        let shouldRestore = !keepOnClipboard
        // Even when copying is enabled, an aborted paste must not replace the user's
        // clipboard. A successful paste preserves the existing keep-on-clipboard policy.
        let snapshotStarted = ProcessInfo.processInfo.systemUptime
        let previousSnapshot = snapshotPasteboard()
        logDuration("clipboard_snapshot", since: snapshotStarted)

        let writeStarted = ProcessInfo.processInfo.systemUptime
        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)

        if shouldRestore {
            // Signal to all macOS clipboard managers (Raycast, Alfred, Maccy, Paste, CleanClip, etc.)
            // that this is a transient/auto-generated paste and MUST NOT be recorded into history.
            item.setString("", forType: transientType)
            item.setString("", forType: concealedType)
            item.setString("", forType: autoGeneratedType)
        }

        pasteboard.writeObjects([item])
        let changeCountAfterWrite = pasteboard.changeCount
        logDuration("clipboard_write", since: writeStarted)

        // Wait 25ms for the macOS pasteboard server to register the new item before sending Cmd+V
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.025) {
            let finalCheckStarted = ProcessInfo.processInfo.systemUptime
            let currentCheck = target?.isCurrent == true
            self.logDuration("final_focus", since: finalCheckStarted)
            guard currentCheck,
                  shouldInsert?() != false,
                  pasteboard.changeCount == changeCountAfterWrite else {
                // Do not overwrite anything the user copied during the delay.
                let restoreStarted = ProcessInfo.processInfo.systemUptime
                if pasteboard.changeCount == changeCountAfterWrite {
                    self.restorePasteboard(from: previousSnapshot)
                }
                self.logDuration("abort_restore", since: restoreStarted)
                self.logDuration("total", since: insertionStarted)
                completion?(false)
                return
            }
            let pasteStarted = ProcessInfo.processInfo.systemUptime
            self.sendPasteKeystroke()
            self.logDuration("paste_dispatch", since: pasteStarted)
            self.logDuration("time_to_paste", since: insertionStarted)

            if shouldRestore {
                // Allow the target application 180ms to read from the pasteboard, then restore prior clipboard
                DispatchQueue.main.asyncAfter(deadline: .now() + 0.18) {
                    // Safety check: Only restore if the user hasn't copied something else in those 180ms
                    let restoreStarted = ProcessInfo.processInfo.systemUptime
                    if pasteboard.changeCount == changeCountAfterWrite {
                        self.restorePasteboard(from: previousSnapshot)
                    }
                    self.logDuration("clipboard_restore", since: restoreStarted)
                    self.logDuration("total", since: insertionStarted)
                    completion?(true)
                }
            } else {
                self.logDuration("total", since: insertionStarted)
                completion?(true)
            }
        }
        return true
    }

    /// Synthesizes Command + V keypress events into the focused application
    public func sendPasteKeystroke() {
        let vKeyCode: CGKeyCode = 9 // 'v' virtual key code on macOS

        let source = CGEventSource(stateID: .combinedSessionState)
        let keyDown = CGEvent(keyboardEventSource: source, virtualKey: vKeyCode, keyDown: true)
        keyDown?.flags = .maskCommand

        let keyUp = CGEvent(keyboardEventSource: source, virtualKey: vKeyCode, keyDown: false)
        keyUp?.flags = .maskCommand

        keyDown?.post(tap: .cghidEventTap)
        keyUp?.post(tap: .cghidEventTap)
    }

    /// Synthesizes Command + Z keypress events into the focused application to undo the previous action
    public func sendUndoKeystroke() {
        let zKeyCode: CGKeyCode = 6 // 'z' virtual key code on macOS

        let source = CGEventSource(stateID: .combinedSessionState)
        let keyDown = CGEvent(keyboardEventSource: source, virtualKey: zKeyCode, keyDown: true)
        keyDown?.flags = .maskCommand

        let keyUp = CGEvent(keyboardEventSource: source, virtualKey: zKeyCode, keyDown: false)
        keyUp?.flags = .maskCommand

        keyDown?.post(tap: .cghidEventTap)
        keyUp?.post(tap: .cghidEventTap)
    }
}
